Fix: Organization cards on landing page visual bug
climateconnect/climateconnect pull request #1028
Opened 2022-08-11 15:00 UTC by JoshKornfeld

## Description

Solves #1026 

- If an organization has more than 1 type, the chips will stack on top of each other rather than be next to each other
- The summary text now goes into the next line and will cut off like it does in /browse#organizations

## Test plan

- Visit the landing page
- Scroll down to "Find a climate action organization and get involved"
- The cards should be visible there

## Before landing

1. PR has meaningful title
1. `yarn lint` passes (frontend)
1. `yarn format` passes (frontend)
1. `make format` passes (backend)

2022-08-11 15:02 UTC, JoshKornfeld commented on frontend/src/components/organization/OrganizationPreview.js
> +      backgroundColor: "#f7f7f7", // f7f7f7
```suggestion
      backgroundColor: "#f7f7f7"
```

2022-08-11 15:02 UTC, JoshKornfeld commented on frontend/src/components/organization/OrganizationPreview.js
> +      backgroundColor: "#f7f7f7", // f7f7f7
Forgot to delete a comment while testing things

2022-08-17 04:26 UTC, ddhanesha requested changes

2022-08-17 04:26 UTC, ddhanesha commented on frontend/src/components/organization/OrganizationPreviewHeader.js
> +      marginTop: props.numOfTypes > 1 ? 0 : 21,
What is 21 here? How did you define that number?

2022-08-17 04:26 UTC, ddhanesha commented on frontend/src/components/organization/OrganizationPreviewHeader.js
> +    numOfTypes: organization.types.length,
I think better variable name would be `orgTypeLength`.

2022-08-27 18:31 UTC, ddhanesha approved these changes
Let's get this merged!

2022-08-27 18:33 UTC, merged