Feat: Label indicating a reply must be sent in chatbox
climateconnect/climateconnect pull request #1149
Opened 2022-11-18 17:12 UTC by JoshKornfeld

## Description

## Test plan

## Before landing

1. PR has meaningful title
1. `yarn lint` passes (frontend)
1. `yarn format` passes (frontend)
1. `make format` passes (backend)

2022-11-21 14:15 UTC, JoshKornfeld commented on frontend/src/components/communication/chat/ChatPreviews.js
> +  console.log(user);
```suggestion

```

2022-11-23 04:10 UTC, ddhanesha requested changes
You made a good try but I don't think we need to add a role column to user_profile table to show a label. There is a better way to show the label. You fetch user_id of the last message sent in a chat. Then compare the id of the user calling the API and user_id of the last message. If the user_id does not match then you show the message.

2022-11-23 07:51 UTC, JoshKornfeld commented
> You made a good try but I don't think we need to add a role column to user_profile table to show a label. There is a better way to show the label. You fetch user_id of the last message sent in a chat. Then compare the id of the user calling the API and user_id of the last message. If the user_id does not match then you show the message.

We wanted to make this only available to certain users like Thomas, as this is a tool for community building. If this was for regular users we would need to add a way to dismiss the label for the cases in which their conversation is over for the time being and the label may become annoying to those users.

2022-11-25 02:32 UTC, ddhanesha commented
> > You made a good try but I don't think we need to add a role column to user_profile table to show a label. There is a better way to show the label. You fetch user_id of the last message sent in a chat. Then compare the id of the user calling the API and user_id of the last message. If the user_id does not match then you show the message.
> 
> We wanted to make this only available to certain users like Thomas, as this is a tool for community building. If this was for regular users we would need to add a way to dismiss the label for the cases in which their conversation is over for the time being and the label may become annoying to those users.

I don't think we established that this requirement should only be for climate connect community building. I believe this can be a very useful tool for everyone on the platform.

2022-11-25 15:05 UTC, JoshKornfeld commented
@ddhanesha I agree that this feature could be useful to regular users. I've removed the role column and instead introduced a slider which state is stored in a cookie. Hopefully, this will enable users to also use this feature, without annoying users who do not want to use it. 
In the prior implementation, I had discussed with @positiveimpact what to do about hiding the label for users who didn't need it i.e. in the case a chat had some to its natural conclusion for the time being. We concluded that we could just make this available to certain users like Thomas and avoid needing the ability to turn it off, hence the introduction of the role column. I hope this is a good middle ground :)

2025-03-18 08:51 UTC, positiveimpact commented
Archiving this because it's now too far removed from our current codebase.

2025-03-18 08:51 UTC, closed without merging